force-app/main/default/objects/QRtoLeadMapping__mdt/QRtoLeadMapping__mdt.object-meta.xml
<CustomObject>
    <description>This object stores the mappings of vCard property names to Lead field names.</description>
    <label>QR-to-Lead Mapping</label>
    <pluralLabel>QR-to-Lead Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/QRtoLeadMapping__mdt/fields/DefaultValue__c.field-meta.xml
<CustomField>
    <fullName>DefaultValue__c</fullName>
    <description>This value is used when creating the Lead record if the specified vCard property isn&apos;t found in the QR code.</description>
    <inlineHelpText>This value is used when creating the Lead record if the specified vCard property isn&apos;t found in the QR code.</inlineHelpText>
    <label>Default Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QRtoLeadMapping__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this mapping is enabled and will be used during QR code processing.</description>
    <inlineHelpText>Indicates whether this mapping is enabled and will be used during QR code processing.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QRtoLeadMapping__mdt/fields/IsRequired__c.field-meta.xml
<CustomField>
    <fullName>IsRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this mapping is required in order for the QR code&apos;s scan to be considered valid for further processing.</description>
    <inlineHelpText>Indicates whether this mapping is required in order for the QR code&apos;s scan to be considered valid for further processing.</inlineHelpText>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QRtoLeadMapping__mdt/fields/LeadFieldName__c.field-meta.xml
<CustomField>
    <fullName>LeadFieldName__c</fullName>
    <description>The name of the Lead field that will receive specific vCard data.</description>
    <inlineHelpText>The name of the Lead field that will receive specific vCard data.</inlineHelpText>
    <label>Lead Field Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QRtoLeadMapping__mdt/fields/vCardPropertyName__c.field-meta.xml
<CustomField>
    <fullName>vCardPropertyName__c</fullName>
    <description>The name of the vCard property that is used to capture specific vCard data.</description>
    <inlineHelpText>The name of the vCard property that is used to capture specific vCard data.</inlineHelpText>
    <label>vCard Property Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QRtoLeadController.cls
/**
 * Serves as the controller for the QR-to-Lead LWC.
 */
public with sharing class QRtoLeadController {

    /**
     * Returns a map of the active QR-to-Lead mappings.
     * 
     * @return the active mappings
     */
    @AuraEnabled(cacheable=true)
    public static Map<String, QRtoLeadMapping__mdt> getKeyedVCardLeadMappings() {
        Map<String, QRtoLeadMapping__mdt> mappingsByVCardProperty = new Map<String, QRtoLeadMapping__mdt>();
        try {
            for (QRtoLeadMapping__mdt mapping : [SELECT vCardPropertyName__c, LeadFieldName__c, DefaultValue__c, IsActive__c, IsRequired__c
                    FROM QRtoLeadMapping__mdt
                    WHERE IsActive__c = TRUE]) {
                mappingsByVCardProperty.put(mapping.vCardPropertyName__c, mapping);
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return mappingsByVCardProperty;
    }

    /**
     * Answers whether the scanned lead already exists for the current user through a simple matching rule.
     * 
     * This check prevents duplicate leads from being created.
     * 
     * @return true if the user already has this lead
     */
    @AuraEnabled(cacheable=false)
    public static Boolean isLeadNew(QRtoLeadWrapper leadToCheck) {
        Integer count = [SELECT count()
                        FROM Lead
                        WHERE OwnerId = :UserInfo.getUserId() AND
                        LastName = :leadToCheck.lastName AND
                        Email = :leadToCheck.email];

        return count == 0;
    }

}